# Generated by Django 2.2.6 on 2019-10-20 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50)),
                ('tradeInfo', models.CharField(max_length=50)),
                ('tradePrice', models.CharField(max_length=300)),
                ('tradeTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('userPassword', models.CharField(max_length=100)),
                ('userName', models.CharField(max_length=50)),
                ('userPhone', models.CharField(max_length=100)),
                ('publicKey', models.CharField(max_length=32)),
                ('privateKey', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=5)),
            ],
        ),
    ]
