# Generated by Django 2.2.6 on 2019-10-23 10:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramUser',
            fields=[
                ('userId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('userPassword', models.CharField(max_length=100)),
                ('userName', models.CharField(max_length=50)),
                ('userPhone', models.CharField(max_length=100)),
                ('publicKey', models.CharField(max_length=32)),
                ('privateKey', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50)),
                ('tradeInfo', models.CharField(max_length=50)),
                ('tradePrice', models.IntegerField(default=0)),
                ('tradeTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('TradeUserId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bithumb.ProgramUser')),
            ],
        ),
    ]
