# Generated by Django 2.2.6 on 2019-10-20 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bithumb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradehistory',
            name='TradeUserId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bithumb.User'),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='tradePrice',
            field=models.IntegerField(default=0),
        ),
    ]
