# Generated by Django 2.2.6 on 2019-10-24 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bithumb', '0002_tradescheduler'),
    ]

    operations = [
        migrations.AddField(
            model_name='programuser',
            name='mySchedulerId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tradescheduler',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bithumb.ProgramUser'),
        ),
        migrations.AlterField(
            model_name='tradescheduler',
            name='schedulerId',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
