# Generated by Django 2.2.6 on 2019-10-22 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bithumb', '0003_auto_20191020_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradehistory',
            name='TradeUserId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bithumb.USER'),
        ),
    ]
