# Generated by Django 2.2.6 on 2019-10-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bithumb', '0003_auto_20191025_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programuser',
            name='mySchedulerId',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tradescheduler',
            name='schedulerId',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
