# Generated by Django 2.2.6 on 2019-10-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bithumb', '0004_auto_20191025_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programuser',
            name='mySchedulerId',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
