# Generated by Django 2.2.6 on 2019-10-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bithumb', '0004_auto_20191023_0030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='ProgramUser',
        ),
    ]
