# Generated by Django 2.2.6 on 2019-10-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bithumb', '0010_auto_20191026_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradehistory',
            name='tradeCount',
            field=models.FloatField(default=0),
        ),
    ]
