# Generated by Django 2.2.6 on 2019-11-07 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bithumb', '0011_auto_20191027_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programuser',
            name='privateKey',
        ),
        migrations.RemoveField(
            model_name='programuser',
            name='publicKey',
        ),
        migrations.CreateModel(
            name='APILicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bit_publicKey', models.CharField(max_length=100)),
                ('bit_privateKey', models.CharField(max_length=100)),
                ('tw_publicKey', models.CharField(max_length=100)),
                ('tw_privateKey', models.CharField(max_length=100)),
                ('tw_number', models.CharField(max_length=100)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bithumb.ProgramUser')),
            ],
        ),
    ]
