# Generated by Django 2.2.6 on 2019-11-17 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bithumb', '0014_auto_20191113_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=500)),
                ('TIME', models.DateTimeField(default=django.utils.timezone.now)),
                ('BTC', models.CharField(max_length=500)),
                ('ETH', models.CharField(max_length=500)),
                ('XRP', models.CharField(max_length=500)),
                ('BCH', models.CharField(max_length=500)),
                ('LTC', models.CharField(max_length=500)),
                ('EOS', models.CharField(max_length=500)),
                ('BSV', models.CharField(max_length=500)),
                ('XLM', models.CharField(max_length=500)),
                ('TRX', models.CharField(max_length=500)),
            ],
        ),
    ]
