# Generated by Django 2.2.6 on 2019-11-19 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bithumb', '0015_tickerprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradescheduler',
            name='schedulerKind',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ShortTermScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeType', models.CharField(max_length=50)),
                ('tradePrice', models.IntegerField(default=0)),
                ('tradeCount', models.FloatField(default=0)),
                ('firstBuyPrice', models.IntegerField(default=0)),
                ('upperCount', models.IntegerField(default=0)),
                ('lowerCount', models.IntegerField(default=0)),
                ('checkCount', models.IntegerField(default=0)),
                ('schedulerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bithumb.TradeScheduler')),
            ],
        ),
    ]
